server.port=8081

spring.application.name=auth-service

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=civic_user
spring.datasource.password=civic_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=9266966545388243656A6F4E3978324164644538476B6B5664566F5970337336
app.jwt.expiration-ms=86400000
