server.port=8080

spring.application.name=complaint-service

spring.datasource.url=jdbc:h2:mem:civicdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.secret=9266966545388243656A6F4E3978324164644538476B6B5664566F5970337336
app.jwt.expiration-ms=86400000

# ==========================================================
# GMAIL GMAIL OAUTH2 EMAIL CONFIGURATION
# ==========================================================
google.oauth2.client-json-location=classpath:google-oauth-client.json
google.oauth2.refresh-token=${GOOGLE_OAUTH2_REFRESH_TOKEN:}
google.oauth2.sender-email=${GOOGLE_OAUTH2_SENDER_EMAIL:sreemathigokila@gmail.com}
google.oauth2.sender-name=CivicConnect

# ==========================================================
# OPENAI CONFIGURATION
# ==========================================================

openai.api-key=${OPENAI_API_KEY:}
openai.model=${OPENAI_MODEL:gpt-4o-mini}
